{
 "title": "ELEMT Pool",
 "description": "Elemental Pool Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{alias=\"block-producer-cardano-node\"} * 100",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_density_real{alias=\"relay-1-cardano-node\"} * 100",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Core Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"block-producer\"}[1m])) * 100)",
     "legendFormat": "CPU Core"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer\"})",
     "legendFormat": "Disk Core"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer\"} / (node_memory_MemTotal_bytes{alias=\"block-producer\"})))* 100",
     "legendFormat": "RAM Core"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"block-producer\"} / node_memory_SwapTotal_bytes{alias=\"block-producer\"})) * 100",
     "legendFormat": "SWAP Core"
    }
   ]
  },
  {
   "title": "Peers (Core)",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peers_connectedPeers_int{alias=\"block-producer-cardano-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Core TX's processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"block-producer-cardano-node\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"block-producer-cardano-node\"} / (1000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"block-producer-cardano-node\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Relay Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relay-1\"}[1m])) * 100)",
     "legendFormat": "CPU Relay 1"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay-1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay-1\"})",
     "legendFormat": "Disk Relay 1"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay-1\"} / (node_memory_MemTotal_bytes{alias=\"relay-1\"})))* 100",
     "legendFormat": "RAM Relay 1"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"relay-1\"} / node_memory_SwapTotal_bytes{alias=\"relay-1\"})) * 100",
     "legendFormat": "SWAP Relay 1"
    }
   ]
  },
  {
   "title": "Peers (Relay)",
   "type": "timeseries",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_incomingConns{alias=\"relay-1-cardano-node\"}",
     "legendFormat": "Relay1_IncomingConns"
    },
    {
     "expr": "cardano_node_metrics_connectionManager_outgoingConns{alias=\"relay-1-cardano-node\"}",
     "legendFormat": "Relay1_OutgoingConns"
    }
   ]
  },
  {
   "title": "Relay TX's processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"relay-1-cardano-node\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"relay-1-cardano-node\"} / (1000)",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_node_not_leader_int{alias=\"block-producer-cardano-node\"} / cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"block-producer-cardano-node\"} * 100)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "KES Key : Days Left",
   "type": "gauge",
   "description": "Remaining KES DAYS before we need to rotate keys",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"block-producer-cardano-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relay-1-cardano-node\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-cardano-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relay-1-cardano-node\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode2\"}",
     "legendFormat": "Relay2"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode3\"}",
     "legendFormat": "Relay3"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relaynode4\"}",
     "legendFormat": "Relay4"
    }
   ]
  },
  {
   "title": "KES Key Rotation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "Current Period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expiry Period"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"block-producer-cardano-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"block-producer\"}[1m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relay-1\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current \"Residency\" (amount of live data)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"block-producer-cardano-node\"}/(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay-1-cardano-node\"}/(1024*1024)",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "System Load (Core Node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "node_load1{alias=\"block-producer\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"block-producer\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"block-producer\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay Node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "node_load1{alias=\"relay-1\"}*100",
     "legendFormat": "R1 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relay-1\"}*100",
     "legendFormat": "R1 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relay-1\"}*100",
     "legendFormat": "R1 Load 15m"
    },
    {
     "expr": "node_load1{alias=\"relaynode2\"}*100",
     "legendFormat": "R2 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode2\"}*100",
     "legendFormat": "R2 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode2\"}*100",
     "legendFormat": "R2 Load 15m"
    },
    {
     "expr": "node_load1{alias=\"relaynode3\"}*100",
     "legendFormat": "R3 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode3\"}*100",
     "legendFormat": "R3 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode3\"}*100",
     "legendFormat": "R3 Load 15m"
    },
    {
     "expr": "node_load1{alias=\"relaynode4\"}*100",
     "legendFormat": "R4 Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relaynode3\"}*100",
     "legendFormat": "R4 Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relaynode4\"}*100",
     "legendFormat": "R4 Load 15m"
    }
   ]
  },
  {
   "title": "Time Synchronization (Core Node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"block-producer\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"block-producer\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"block-producer\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay1 Node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relay-1\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relay-1\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relay-1\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Memory Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer\"} / (node_memory_MemTotal_bytes{alias=\"block-producer\"})))* 100",
     "legendFormat": "Core"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay-1\"} / (node_memory_MemTotal_bytes{alias=\"relay-1\"})))* 100",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Block Sync Speed (blocks / min)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"block-producer-cardano-node\"}[150s]) *60",
     "legendFormat": "Core"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relay-1-cardano-node\"}[150s]) *60",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "timeseries",
   "description": "current",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"block-producer-cardano-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay-1-cardano-node\"}",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Peak Memory Allocated",
   "type": "timeseries",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"block-producer-cardano-node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay-1-cardano-node\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Aggregate Data Transfer",
   "type": "timeseries",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"block-producer\"}[1h])) * 3600",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relay-1\"}[1h])) * 3600",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Max \"Residency\"",
   "type": "timeseries",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"block-producer-cardano-node\"} /(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay-1-cardano-node\"} /(1024*1024)",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"block-producer\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "node_filefd_allocated{alias=\"relay-1\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "RSS (allocated memory in RAM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"block-producer-cardano-node\"}*4096)/(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"relay-1-cardano-node\"}*4096)/(1024*1024)",
     "legendFormat": "Relay1"
    }
   ]
  }
 ]
}