services:
  cardano-node-relay:
    image: ghcr.io/intersectmbo/cardano-node:10.3.1
    container_name: cardano-node-relay
    ports:
      - 6000:6000 # Cardano node relay port
      - 12798:12798 # Cardano node metrics
    volumes:
      - ./node/db/:/node/db
      - ./node/ipc/:/node/ipc
      - ./node/configuration:/node/configuration
      - ./scripts:/scripts
    environment:
      - NETWORK=--mainnet
      - MAGIC_NUMBER=764824073
      - CARDANO_NODE_SOCKET_PATH=/node/ipc/node.socket
    restart: always
    entrypoint: /scripts/run-cardano-node.sh

  node_exporter: # Listening by default on port 9100
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    depends_on:
      - cardano-node-relay

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    depends_on:
      - node_exporter

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: '0'
    ports:
      - 3000:3000 # Grafana monitor port
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
